adaptive_scan:
  atr_baseline: 0.005
  enabled: true
  max_factor: 10.0
adx_threshold: 15
allow_short: true
arbitrage_enabled: true
atr_normalization: true
balance_poll_mod: 1
bandit:
  alpha0: 1
  beta0: 1
  enabled: false
  explore_pct: 0.1
bb_squeeze_pct: 10
bounce_scalper:
  atr_normalization: true
  atr_period: 10
  atr_window: 10
  cooldown_enabled: false
  down_candles: 2
  ema_window: 40
  lookback: 200
  max_concurrent_signals: 8
  min_score: 0.2
  overbought: 75
  oversold: 25
  pattern_timeframe: 1m
  rsi_overbought_pct: 75
  rsi_oversold_pct: 25
  rsi_window: 14
  stop_loss_atr_mult: 1.0
  take_profit_atr_mult: 2.0
  trend_ema_fast: 8
  trend_ema_slow: 18
  up_candles: 2
  vol_window: 15
  vol_zscore_threshold: 2.0
  volume_multiple: 1.5
  zscore_threshold: 1.0
breakout:
  adx_threshold: 15
  atr_buffer_mult: 0.03
  bb_length: 10
  bb_std: 1.5
  dc_length: 15
  kc_length: 10
  kc_mult: 1.0
  momentum_filter: false
  squeeze_threshold: 0.01
  vol_multiplier: 1.0
  volume_window: 15
cycle_bias:
  enabled: true
  mvrv_url: https://api.alternative.me/v2/onchain/mvrv
  nupl_url: https://api.alternative.me/v2/onchain/nupl
  sopr_url: https://api.alternative.me/v2/onchain/sopr
cycle_lookback_limit: 150
drawdown_penalty_coef: 0.2
ensemble_min_conf: 0.1
exchange: kraken
exchange_market_types:
- spot
- futures
excluded_symbols: []
exec:
  allow_market_orders: true
  order_retry_interval: 3
execution_mode: dry_run
exit_strategy:
  fib_tp_enabled: true
  min_gain_to_trail: 0.01
  partial_levels:
  - 25
  - 50
  - 75
  - 100
  scale_out: true
  trailing_stop_factor: 1.2
  trailing_stop_pct: 0.02
  take_profit_pct: 0.05  # 5% take profit
  # Short-specific settings
  short_trailing_stop_pct: 0.02
  short_take_profit_pct: 0.05
  short_stop_loss_pct: 0.015
exits:
  default_sl_pct: 0.015
  default_tp_pct: 0.07
  trailing_stop_pct: 0.02
force_websocket_history: false
gas_threshold_gwei: 50
grid_bot:
  arbitrage_pairs:
  - BTC/USDT
  - SOL/USDC
  arbitrage_threshold: 0.001
  atr_normalization: true
  atr_period: 10
  breakout_mult: 1.0
  cooldown_bars: 1
  dynamic_grid: true
  leverage: 2
  max_active_legs: 12
  min_range_pct: 0.0003
  range_window: 15
  spacing_factor: 0.2
  trend_ema_fast: 40
  trend_ema_slow: 150
  use_ml_center: true
  vol_zscore_threshold: 1.5
  volume_filter: false
  volume_ma_window: 15
  volume_multiple: 1.0
hidden_limit: true
indicator_lookback: 14
liquidity_check: true
liquidity_depth: 5
log_to_google: true
loop_interval_minutes: 0.5
max_age_days: 90
max_change_pct: 20
max_concurrent_ohlcv: 4
max_latency_ms: 500
max_ohlcv_failures: 10
max_open_trades: 5
max_parallel: 50
max_slippage_pct: 0.2
max_spread_pct: 3
max_vol: 50000000
max_ws_limit: 200
# Timeout configuration for OHLCV data fetching
ws_ohlcv_timeout: 30  # WebSocket timeout in seconds (reduced from default 60)
rest_ohlcv_timeout: 45  # REST API timeout in seconds (reduced from default 90)

# OHLCV data quality configuration
ohlcv_quality:
  min_data_ratio: 0.7  # Minimum ratio of expected vs actual data (70%)
  min_required_candles: 50  # Minimum candles required for analysis
  retry_incomplete: true  # Retry fetching incomplete data
  fallback_to_rest: true  # Fallback to REST API for incomplete WebSocket data
meme_wave_sniper:
  enabled: true
  execution:
    dry_run: true
  pool:
    interval: 3
    raydium_program_id: EhhTK0i58FmSPrbr30Y8wVDDDeWGPAHDq6vNru6wUATk
    url: https://mainnet.helius-rpc.com/v1/?api-key=${HELIUS_KEY}
    websocket_url: wss://mainnet.helius-rpc.com/?api-key=${HELIUS_KEY}
  risk:
    daily_loss_cap: 2.0
    max_concurrent: 15
  risk_file: crypto_bot/logs/sniper_risk.json
  safety:
    min_liquidity: 5
  scoring:
    weight_liquidity: 0.8
    weight_social: 0.7
    weight_tx: 1.2
mempool_monitor:
  action: reprice
  enabled: true
  reprice_multiplier: 1.1
  suspicious_fee_threshold: 30
meta_selector:
  enabled: false
metrics_backend: csv
metrics_enabled: true
metrics_output_file: crypto_bot/logs/metrics.csv
micro_scalp:
  atr_period: 10
  confirm_bars: 0
  ema_fast: 2
  ema_slow: 4
  fresh_cross_only: false
  imbalance_filter: false
  imbalance_penalty: 0.1
  imbalance_ratio: 0
  min_atr_pct: 0.0005
  min_momentum_pct: 0.0
  min_vol_z: -1.0
  trend_fast: 15
  trend_filter: false
  trend_slow: 40
  trend_timeframe: 1m
  vol_window: 15
  volume_window: 15
  wick_pct: 0.1
min_agreeing_votes: 1
min_confidence_score: 0.05
min_consistent_agreement: 1
min_cooldown: 0
min_symbol_age_days: 0
min_symbol_score: 0
ml_enabled: true
ml_signal_model:
  enabled: true
  weight: 0.7
mode: auto
mode_degrade_window: 15
mode_threshold: 0.3
ohlcv_snapshot_frequency_minutes: 720
ohlcv_snapshot_limit: 500
ohlcv_timeout: 300
optimization:
  enabled: true
  interval_days: 1  # Run daily for better optimization
  parameter_ranges:
    trend:
      stop_loss: [0.01, 0.015, 0.02, 0.025, 0.03]
      take_profit: [0.02, 0.03, 0.04, 0.05, 0.06, 0.08]
    momentum_bot:
      stop_loss: [0.01, 0.015, 0.02, 0.025]
      take_profit: [0.025, 0.035, 0.05, 0.07]
    grid_bot:
      stop_loss: [0.005, 0.01, 0.015, 0.02]
      take_profit: [0.01, 0.02, 0.03, 0.04]
    bounce_scalper:
      stop_loss: [0.005, 0.01, 0.015]
      take_profit: [0.015, 0.025, 0.035]
    sniper_bot:
      stop_loss: [0.008, 0.012, 0.018, 0.025]
      take_profit: [0.02, 0.03, 0.045, 0.06]
portfolio_rotation:
  enabled: true
  interval_days: 0.5
  rebalance_threshold: 0.05
  scoring_method: sharpe
  top_assets: 20

# Enhanced Backtesting Configuration
enhanced_backtesting:
  enabled: true
  continuous_mode: false  # Set to true for continuous backtesting
  top_pairs_count: 15
  min_volume_usd: 500000
  refresh_interval_hours: 12
  lookback_days: 60
  timeframes: ["1h", "4h"]
  strategies_to_test: ["trend", "momentum_bot", "grid_bot", "bounce_scalper", "sniper_bot"]
  use_gpu: false  # Set to true if you have GPU acceleration
  batch_size: 50
  max_workers: 4
  results_cache_dir: "crypto_bot/logs/backtest_results"
  max_drawdown_threshold: 0.4
  min_sharpe_threshold: 0.3
  min_win_rate: 0.35
preferred_chain: solana
pyth:
  enabled: true
  program_id: FsJ3A3u2vn5cTVofAjvy6qM3HrjTXg5Gs1Y8D6fCt3m
  solana_endpoint: https://api.mainnet-beta.solana.com
  solana_ws_endpoint: wss://api.mainnet-beta.solana.com
refresh_pairs:
  allowed_quote_currencies: []
  blacklist_assets: []
  min_quote_volume_usd: 1000
  refresh_interval: 30m
  top_k: 100
regime_return_period: 3
regime_timeframes:
- 1m
- 5m
- 15m
- 1h
- 4h
risk:
  atr_long_window: 40
  atr_period: 10
  atr_short_window: 10
  max_drawdown: 0.5
  max_volatility_factor: 3
  min_expected_value: -0.1
  min_volume: 0.1
  stop_loss_atr_mult: 1.5
  stop_loss_pct: 0.015  # 1.5% hard stop loss - ALWAYS enforced
  take_profit_atr_mult: 3.0
  take_profit_pct: 0.07  # 7% take profit for both long and short
  volume_threshold_ratio: 0.0001
  
  # Emergency stop loss settings
  emergency_stop_loss_pct: 0.025  # 2.5% emergency stop loss
  force_exit_on_stop_loss: true   # Always exit when stop loss is hit
  ignore_momentum_on_stop_loss: true  # Ignore momentum checks for stop losses
  
  # Trailing stop improvements
  trailing_stop_protect_losses: true  # Allow trailing stops to protect against losses
  min_trailing_stop_distance: 0.005  # Minimum 0.5% trailing stop distance
  # Short-specific risk parameters
  short_stop_loss_pct: 0.015
  short_take_profit_pct: 0.07
  short_trailing_stop_pct: 0.02
  # Position sizing
  trade_size_pct: 0.1
  max_open_trades: 5
  # Margin requirements for short positions
  short_margin_requirement: 1.5  # 150% margin requirement for shorts
  max_short_exposure: 0.3  # Maximum 30% of portfolio in short positions
rl_selector:
  enabled: false
rsi_overbought_pct: 80
rsi_oversold_pct: 25
safety:
  max_error_count: 10
  restart_on_error: true
scalp_timeframe: 1m
scan_in_background: true
scan_lookback_limit: 700
scan_markets: true
scoring:
  lookback_bars: 30
  method: win_rate
  use_numba_scoring: true
scoring_weights:
  regime_confidence: 0.15
  spread_penalty: -0.05
  strategy_regime_strength: 0.25
  strategy_score: 0.5
  symbol_score: 0.05
  volume_score: 0.05
secondary_exchange: coinbase
sentiment_filter:
  bull_fng: 50
  bull_sentiment: 45
  min_fng: -100
  min_sentiment: -100
signal_fusion:
  enabled: false
  fusion_method: weight
  min_confidence: 0.05
  strategies:
  - - trend
    - 0.5
  - - micro_scalp
    - 0.3
  - - sniper_bot
    - 0.2
signal_threshold: 0.05
signal_weight_optimizer:
  enabled: true
  learning_rate: 0.05
  min_weight: 0.01
skip_symbol_filters: false
sl_mult: 1.0
sl_pct: 0.02
sniper_bot:
  atr_window: 10
  breakout_pct: 0.03
  fallback_atr_mult: 1.2
  fallback_volume_mult: 1.0
  max_history: 20
  price_fallback: true
  volume_multiple: 1.2
  volume_window: 3
solana_scalping:
  macd_fast: 10
  macd_signal: 8
  macd_slow: 24
  overbought: 75.0
  oversold: 25.0
  rsi_window: 12
solana_scanner:
  api_keys:
    bitquery: ${BITQUERY_API_KEY}
    moralis: ${MORALIS_API_KEY}
  enabled: true
  gecko_search: true
  interval_minutes: 0.5
  max_tokens_per_scan: 100
  min_volume_usd: 1000
solana_slippage_bps: 10
solana_symbols: []
strategy_allocation:
  grid_bot: 0.2
  sniper_bot: 0.4
  trend_bot: 0.4
strategy_evaluation_mode: ensemble
strategy_router:
  bandit_enabled: false
  bounce_timeframe: 5m
  breakout_timeframe: 15m
  fast_path:
    breakout_max_bandwidth: 0.03
    breakout_squeeze_window: 10
    breakout_volume_multiplier: 3
    trend_adx_threshold: 20
  mean_reverting_timeframe: 1h
  regimes:
    bounce:
    - bounce_scalper
    breakout:
    - breakout_bot
    mean-reverting:
    - mean_bot
    - dip_hunter
    - stat_arb_bot
    scalp:
    - micro_scalp
    sideways:
    - grid
    - maker_spread
    - range_arb_bot
    trending:
    - trend
    - momentum_bot
    - lstm_bot
    volatile:
    - sniper_bot
    - sniper_solana
    - flash_crash_bot
    - meme_wave_bot
    - hft_engine
  scalp_timeframe: 1m
  sideways_timeframe: 1h
  trending_timeframe: 1h
  volatile_timeframe: 1m
symbol: BTC/USDT
symbol_batch_size: 50
symbol_filter:
  change_pct_percentile: 5
  correlation_max_pairs: 200
  http_timeout: 5
  kraken_batch_size: 200
  log_ticker_exceptions: true
  max_correlation: 0.9
  max_spread_pct: 4
  min_volume_usd: 100
  ticker_retry_attempts: 5
  uncached_volume_multiplier: 1.5
  volume_percentile: 10
symbol_refresh_minutes: 1
symbol_score_weights:
  age: 0.02
  change: 0.45
  latency: 0.03
  liquidity: 0.15
  spread: 0.1
  volume: 0.25
symbols: []
tax_tracking:
  enabled: true
  export_path: crypto_bot/logs/tax_trades.csv
telegram:
  chat_admins: 827777274
  chat_id: 827777274
  command_cooldown: 3
  enabled: true
  token: 8126215032:AAEhQZLiXpssauKf0ktQsq1XqXl94QriCdE
  trade_updates: true
  balance_updates: true
  status_updates: true
telegram_ctl:
  enabled: true
  update_interval: 30
testing_mode: true
timeframe: 15m
timeframes:
- 1m
- 5m
- 15m
- 1h
- 4h
top_n_symbols: 50
tp_mult: 2.0
tp_pct: 0.1
trade_size_pct: 0.1
trend:
  atr_period: 10
  k: 0.8
  trend_ema_fast: 15
  trend_ema_slow: 40
twap_enabled: true
twap_interval_seconds: 5
twap_slices: 6
use_websocket: true
volatility_filter:
  max_funding_rate: 0.1
  min_atr_pct: 0.0001
voting_strategies:
- trend
- momentum
- mean_reversion
- sniper_bot
wallet_address: ${WALLET_ADDRESS}
ws_failures_before_disable: 3
ws_ping_interval: 10

# New strategy configurations
cross_chain_arb_bot:
  spread_threshold: 0.02
  pair: ""
  atr_normalization: true

dip_hunter:
  rsi_window: 14
  rsi_oversold: 30.0
  dip_pct: 0.03
  dip_bars: 3
  vol_window: 20
  vol_mult: 1.5
  adx_window: 14
  adx_threshold: 25.0
  bb_window: 20
  ema_trend: 200
  ml_weight: 0.5
  atr_normalization: true
  ema_slow: 20
  cooldown_enabled: false

flash_crash_bot:
  drop_pct: 0.1
  volume_mult: 5.0
  vol_window: 20
  ema_window: 200
  atr_normalization: true

lstm_bot:
  sequence_length: 50
  threshold_pct: 0.0

momentum_bot:
  donchian_window: 20
  volume_window: 20
  volume_z_min: 0.5
  rsi_threshold: 55
  macd_min: 0.0
  fast_length: 12
  slow_length: 26
  atr_normalization: true

range_arb_bot:
  atr_window: 14
  kr_window: 20
  z_threshold: 1.5
  vol_z_threshold: 1.0
  volume_mult: 1.5
  atr_normalization: true

stat_arb_bot:
  zscore_threshold: 2.0
  lookback: 20
  atr_normalization: true

meme_wave_bot:
  volume_threshold: 1.0
  sentiment_threshold: 0.0
  twitter_query: ""
  atr_window: 14
  volume_window: 20
  jump_mult: 3.0
  volume_mult: 3.0
  vol_spike_thr: null

maker_spread:
  size_usd: 1000.0
  tick_size: 0.01
  max_spread_bp: 10.0
  edge_margin_bp: 0.0
  queue_timeout_ms: 5000
  max_live_quotes: 2

hft_engine:
  telemetry:
    batch_summary_secs: 60
  dry_run: true
