# Enhanced configuration for aggressive profit maximization
adaptive_scan:
  atr_baseline: 0.005
  enabled: true
  max_factor: 10.0

# Aggressive regime thresholds for faster switching
adx_threshold: 12  # Reduced from 15 for faster trend detection
allow_short: true
arbitrage_enabled: true
atr_normalization: true
balance_poll_mod: 1

# Enhanced bandit for strategy selection
bandit:
  alpha0: 1
  beta0: 1
  enabled: true  # Enable bandit for dynamic strategy selection
  explore_pct: 0.15  # Increased exploration for finding best strategies

# Optimized breakout detection
bb_squeeze_pct: 8  # Reduced from 10 for earlier breakout detection

# Enhanced bounce scalper with faster exits
bounce_scalper:
  atr_normalization: true
  atr_period: 8  # Reduced from 10 for faster response
  atr_window: 8
  cooldown_enabled: false
  down_candles: 2
  ema_window: 40
  lookback: 200
  max_concurrent_signals: 12  # Increased from 8 for more opportunities
  min_score: 0.15  # Reduced from 0.2 for more signals
  overbought: 75
  oversold: 25
  pattern_timeframe: 1m
  rsi_overbought_pct: 75
  rsi_oversold_pct: 25
  rsi_window: 12  # Reduced from 14 for faster response
  stop_loss_atr_mult: 0.8  # Tighter stops from 1.0
  take_profit_atr_mult: 1.5  # Reduced from 2.0 for faster profits
  trend_ema_fast: 8
  trend_ema_slow: 18
  up_candles: 2
  vol_window: 15
  vol_zscore_threshold: 1.8  # Reduced from 2.0 for more signals
  volume_multiple: 1.5
  zscore_threshold: 0.8  # Reduced from 1.0 for more signals

# Enhanced breakout detection
breakout:
  adx_threshold: 12  # Reduced from 15 for earlier detection
  atr_buffer_mult: 0.02  # Reduced from 0.03 for tighter entries
  bb_length: 10
  bb_std: 1.5
  dc_length: 15
  kc_length: 10
  kc_mult: 1.0
  momentum_filter: true  # Enable momentum filtering
  squeeze_threshold: 0.008  # Reduced from 0.01 for earlier detection
  vol_multiplier: 1.2  # Increased from 1.0 for better confirmation
  volume_window: 15

# Enhanced cycle bias
cycle_bias:
  enabled: true
  mvrv_url: https://api.alternative.me/v2/onchain/mvrv
  nupl_url: https://api.alternative.me/v2/onchain/nupl
  sopr_url: https://api.alternative.me/v2/onchain/sopr

cycle_lookback_limit: 150
drawdown_penalty_coef: 0.15  # Reduced from 0.2 for less penalty
ensemble_min_conf: 0.05  # Reduced from 0.08 for more Solana signals
exchange: kraken
exchange_market_types:
- spot
- futures

excluded_symbols: []

# Enhanced execution settings
exec:
  allow_market_orders: true
  order_retry_interval: 2  # Reduced from 3 for faster execution
  hidden_limit: true  # Enable hidden limit orders for better execution

execution_mode: dry_run

# Enhanced exit strategy for quick profits
exit_strategy:
  fib_tp_enabled: true
  min_gain_to_trail: 0.008  # Reduced from 0.01 for earlier trailing
  partial_levels:
  - 20  # Reduced from 25 for earlier partial exits
  - 40  # Reduced from 50
  - 60  # Reduced from 75
  - 100
  scale_out: true
  trailing_stop_factor: 1.1  # Reduced from 1.2 for tighter trailing
  trailing_stop_pct: 0.015  # Reduced from 0.02 for tighter stops
  take_profit_pct: 0.04  # Reduced from 0.05 for faster profits
  # Short-specific settings
  short_trailing_stop_pct: 0.015
  short_take_profit_pct: 0.04
  short_stop_loss_pct: 0.012  # Reduced from 0.015

# Enhanced exit settings
exits:
  default_sl_pct: 0.012  # Reduced from 0.015 for tighter stops
  default_tp_pct: 0.06  # Reduced from 0.07 for faster profits
  trailing_stop_pct: 0.015  # Reduced from 0.02 for tighter trailing

force_websocket_history: false
gas_threshold_gwei: 50

# Enhanced grid bot for more frequent trades
grid_bot:
  arbitrage_pairs:
  - BTC/USDT
  - SOL/USDC
  arbitrage_threshold: 0.0008  # Reduced from 0.001 for more opportunities
  atr_normalization: true
  atr_period: 8  # Reduced from 10 for faster response
  breakout_mult: 1.2  # Increased from 1.0 for better breakout handling
  cooldown_bars: 1
  grid_levels: 8  # Increased from default for more opportunities
  grid_spacing_pct: 0.008  # Reduced from default for tighter grids
  max_concurrent_trades: 6  # Increased for more opportunities
  min_profit_pct: 0.003  # Reduced from default for faster exits
  volume_filter: true
  volume_multiplier: 1.3  # Increased for better confirmation

# Enhanced mean reversion
mean_bot:
  atr_normalization: true
  atr_period: 8  # Reduced from 10 for faster response
  cooldown_bars: 2  # Reduced from default for more trades
  ema_fast: 12  # Reduced from default for faster signals
  ema_slow: 26  # Reduced from default for faster signals
  lookback: 150  # Reduced from default for faster response
  max_concurrent_signals: 8  # Increased for more opportunities
  min_score: 0.15  # Reduced for more signals
  rsi_overbought: 72  # Reduced from 80 for earlier signals
  rsi_oversold: 28  # Increased from 25 for earlier signals
  rsi_window: 12  # Reduced from default for faster response
  stop_loss_atr_mult: 0.8  # Tighter stops
  take_profit_atr_mult: 1.4  # Reduced for faster profits
  trend_ema_fast: 8
  trend_ema_slow: 21
  vol_window: 15
  vol_zscore_threshold: 1.6  # Reduced for more signals
  volume_multiple: 1.4  # Increased for better confirmation
  zscore_threshold: 0.8  # Reduced for more signals

# Enhanced micro scalping
micro_scalp:
  atr_normalization: true
  atr_period: 6  # Reduced for faster response
  cooldown_bars: 1  # Reduced for more trades
  ema_fast: 5  # Reduced for faster signals
  ema_slow: 13  # Reduced for faster signals
  lookback: 100  # Reduced for faster response
  max_concurrent_signals: 15  # Increased for more opportunities
  min_score: 0.12  # Reduced for more signals
  rsi_overbought: 70  # Reduced for earlier signals
  rsi_oversold: 30  # Increased for earlier signals
  rsi_window: 10  # Reduced for faster response
  stop_loss_atr_mult: 0.6  # Very tight stops for scalping
  take_profit_atr_mult: 1.2  # Quick profits
  trend_ema_fast: 5
  trend_ema_slow: 13
  vol_window: 10  # Reduced for faster response
  vol_zscore_threshold: 1.4  # Reduced for more signals
  volume_multiple: 1.3  # Increased for better confirmation
  zscore_threshold: 0.7  # Reduced for more signals

# Enhanced sniper bot
sniper_bot:
  atr_window: 8  # Reduced from 10 for faster response
  breakout_pct: 0.025  # Reduced from 0.03 for earlier detection
  fallback_atr_mult: 1.0  # Reduced from 1.2 for tighter entries
  fallback_volume_mult: 1.0
  max_history: 15  # Reduced from 20 for faster response
  price_fallback: true
  volume_multiple: 1.3  # Increased from 1.2 for better confirmation
  volume_window: 3

# Enhanced Solana scalping
solana_scalping:
  macd_fast: 8  # Reduced from 10 for faster signals
  macd_signal: 6  # Reduced from 8 for faster signals
  macd_slow: 21  # Reduced from 24 for faster signals
  overbought: 70.0  # Reduced from 75.0 for earlier signals
  oversold: 30.0  # Increased from 25.0 for earlier signals
  rsi_window: 10  # Reduced from 12 for faster response

# Enhanced Solana scanner
solana_scanner:
  api_keys:
    bitquery: ${BITQUERY_API_KEY}
    moralis: ${MORALIS_API_KEY}
    raydium: ${RAYDIUM_API_KEY}
    pump_fun: ${PUMP_FUN_API_KEY}
  enabled: true
  gecko_search: true
  interval_minutes: 0.5  # Increased for more stable scanning
  max_tokens_per_scan: 100  # Balanced for paper trading
  min_volume_usd: 500  # Reduced for more opportunities in paper mode
  min_symbol_score: 0.1  # Lower threshold for paper trading
  fallback_to_test_tokens: true  # Enable fallback for testing

solana_slippage_bps: 8  # Reduced from 10 for better execution
solana_symbols: []

# Enhanced strategy allocation with focus on high-frequency strategies
strategy_allocation:
  grid_bot: 0.15  # Reduced from 0.2
  sniper_bot: 0.25  # Reduced from 0.35
  trend_bot: 0.30  # Reduced from 0.35
  micro_scalp_bot: 0.15  # Added for high-frequency trading
  sniper_solana: 0.15  # Added Solana sniper strategy

strategy_evaluation_mode: ensemble

# Enhanced strategy router with aggressive regime weighting
strategy_router:
  bandit_enabled: true  # Enable bandit for dynamic strategy selection
  bounce_timeframe: 3m  # Reduced from 5m for faster response
  breakout_timeframe: 10m  # Reduced from 15m for faster response
  fast_path:
    breakout_max_bandwidth: 0.025  # Reduced from 0.03 for earlier detection
    breakout_squeeze_window: 8  # Reduced from 10 for faster response
    breakout_volume_multiplier: 3.5  # Increased from 3 for better confirmation
    trend_adx_threshold: 15  # Reduced from 20 for earlier trend detection
  mean_reverting_timeframe: 45m  # Reduced from 1h for faster response
  regimes:
    bounce:
    - bounce_scalper
    - micro_scalp_bot  # Added for faster response
    breakout:
    - breakout_bot
    - sniper_bot  # Added for better breakout capture
    mean-reverting:
    - mean_bot
    - dip_hunter
    - stat_arb_bot
    - grid_bot  # Added for mean reversion
    scalp:
    - micro_scalp_bot
    - bounce_scalper  # Added for scalp regime
    sideways:
    - grid_bot
    - maker_spread
    - range_arb_bot
    trending:
    - trend_bot
    - momentum_bot
    - lstm_bot
    volatile:
    - sniper_bot
    - sniper_solana
    - flash_crash_bot
    - meme_wave_bot
    - micro_scalp_bot  # Added for volatile regime
    - bounce_scalper  # Added for volatile regime
  scalp_timeframe: 30s  # Reduced from 1m for faster scalping
  sideways_timeframe: 45m  # Reduced from 1h for faster response
  trending_timeframe: 45m  # Reduced from 1h for faster response
  volatile_timeframe: 30s  # Reduced from 1m for faster response

# Enhanced signal fusion
signal_fusion:
  enabled: true  # Enable signal fusion
  fusion_method: weight
  min_confidence: 0.04  # Reduced from 0.05 for more signals
  strategies:
  - - trend_bot
    - 0.4  # Reduced from 0.5
  - - micro_scalp_bot
    - 0.4  # Increased from 0.3
  - - sniper_bot
    - 0.2

signal_threshold: 0.02  # Reduced from 0.04 for more Solana signals

# Enhanced signal weight optimizer
signal_weight_optimizer:
  enabled: true
  learning_rate: 0.08  # Increased from 0.05 for faster adaptation
  min_weight: 0.008  # Reduced from 0.01 for more strategy participation

skip_symbol_filters: false
sl_mult: 0.8  # Reduced from 1.0 for tighter stops
sl_pct: 0.015  # Reduced from 0.02 for tighter stops

# Enhanced symbol filtering for more opportunities
symbol_filter:
  change_pct_percentile: 2  # Reduced from 3 for more volatile symbols
  correlation_max_pairs: 200
  http_timeout: 3  # Reduced from 5 for faster response
  kraken_batch_size: 250  # Increased from 200 for more symbols
  log_ticker_exceptions: true
  min_volume_usd: 500  # Reduced for more Solana opportunities
  max_correlation: 0.85  # Reduced from 0.9 for more diverse pairs
  max_spread_pct: 5  # Increased from 4 for more opportunities
  min_volume_usd: 80  # Reduced from 100 for more opportunities
  ticker_retry_attempts: 3  # Reduced from 5 for faster response
  uncached_volume_multiplier: 1.3  # Reduced from 1.5 for more realistic volumes
  volume_percentile: 8  # Reduced from 10 for more opportunities

symbol_refresh_minutes: 0.5  # Reduced from 1 for faster symbol updates

# Enhanced symbol scoring weights
symbol_score_weights:
  age: 0.015  # Reduced from 0.02
  change: 0.5  # Increased from 0.45 for more momentum focus
  latency: 0.025  # Reduced from 0.03
  liquidity: 0.12  # Reduced from 0.15
  spread: 0.08  # Reduced from 0.1
  volume: 0.27  # Increased from 0.25 for more volume focus

symbols: []

# Enhanced tax tracking
tax_tracking:
  enabled: true
  export_path: crypto_bot/logs/tax_trades.csv

# Enhanced Telegram settings
telegram:
  chat_admins: your_telegram_chat_id_here
  chat_id: your_telegram_chat_id_here
  command_cooldown: 2  # Reduced from 3 for faster response
  enabled: true
  token: your_telegram_token_here
  trade_updates: true
  balance_updates: true
  status_updates: true

telegram_ctl:
  enabled: true
  update_interval: 20  # Reduced from 30 for faster updates

testing_mode: true
timeframe: 10m  # Reduced from 15m for faster response
timeframes:
- 30s  # Added for ultra-fast scalping
- 1m
- 5m
- 10m  # Added for faster response
- 15m
- 1h
- 4h

top_n_symbols: 75  # Increased from 50 for more opportunities
symbol_batch_size: 100  # Increased for more Solana opportunities
tp_mult: 1.8  # Reduced from 2.0 for faster profits
tp_pct: 0.08  # Reduced from 0.1 for faster profits
trade_size_pct: 0.12  # Increased from 0.1 for larger positions

# Enhanced trend detection
trend:
  atr_period: 8  # Reduced from 10 for faster response
  k: 0.7  # Reduced from 0.8 for more sensitive trend detection
  trend_ema_fast: 12  # Reduced from 15 for faster signals
  trend_ema_slow: 35  # Reduced from 40 for faster signals

twap_enabled: true
twap_interval_seconds: 3  # Reduced from 5 for faster execution
twap_slices: 8  # Increased from 6 for better execution
use_websocket: true

# Enhanced volatility filtering
volatility_filter:
  max_funding_rate: 0.12  # Increased from 0.1 for more opportunities
  min_atr_pct: 0.00008  # Reduced from 0.0001 for more opportunities

# Logging configuration for debugging
logging:
  level: DEBUG  # Set to DEBUG to see detailed Solana trading information
  console_level: DEBUG
  file_level: INFO

voting_strategies:
- trend_bot
- momentum_bot
- mean_bot
- sniper_bot
- micro_scalp_bot  # Added for high-frequency voting

wallet_address: ${WALLET_ADDRESS}
ws_failures_before_disable: 2  # Reduced from 3 for faster failover
ws_ping_interval: 8  # Reduced from 10 for faster response

# Enhanced new strategy configurations
cross_chain_arb_bot:
  spread_threshold: 0.015  # Reduced from 0.02 for more opportunities
  pair: ""
  atr_normalization: true

dip_hunter:
  rsi_window: 12  # Reduced from 14 for faster response
  rsi_oversold: 28.0  # Increased from 30.0 for earlier signals
  dip_pct: 0.025  # Reduced from 0.03 for earlier detection
  dip_bars: 2  # Reduced from 3 for faster response
  vol_window: 15  # Reduced from 20 for faster response
  vol_mult: 1.6  # Increased from 1.5 for better confirmation
  adx_window: 12  # Reduced from 14 for faster response
  adx_threshold: 22.0  # Reduced from 25.0 for earlier signals
  bb_window: 15  # Reduced from 20 for faster response
  ema_trend: 150  # Reduced from 200 for faster response
  ml_weight: 0.6  # Increased from 0.5 for better ML integration
  atr_normalization: true
  ema_slow: 15  # Reduced from 20 for faster response
  cooldown_enabled: false

flash_crash_bot:
  drop_pct: 0.08  # Reduced from 0.1 for earlier detection
  volume_mult: 6.0  # Increased from 5.0 for better confirmation
  vol_window: 15  # Reduced from 20 for faster response
  ema_window: 150  # Reduced from 200 for faster response
  atr_normalization: true

lstm_bot:
  sequence_length: 40  # Reduced from 50 for faster response
  threshold_pct: -0.002  # Added negative threshold for earlier signals

momentum_bot:
  donchian_window: 15  # Reduced from 20 for faster response
  volume_window: 15  # Reduced from 20 for faster response
  volume_z_min: 0.4  # Reduced from 0.5 for more signals
  rsi_threshold: 52  # Reduced from 55 for earlier signals
  macd_min: -0.001  # Reduced from 0.0 for more signals
  fast_length: 10  # Reduced from 12 for faster signals
  slow_length: 24  # Reduced from 26 for faster signals
  atr_normalization: true

range_arb_bot:
  atr_window: 12  # Reduced from 14 for faster response
  kr_window: 15  # Reduced from 20 for faster response
  z_threshold: 1.3  # Reduced from 1.5 for more signals
  vol_z_threshold: 0.8  # Reduced from 1.0 for more signals
  volume_mult: 1.6  # Increased from 1.5 for better confirmation
  atr_normalization: true

stat_arb_bot:
  zscore_threshold: 1.7  # Reduced from 2.0 for more signals
  lookback: 15  # Reduced from 20 for faster response
  atr_normalization: true

meme_wave_bot:
  volume_threshold: 0.8  # Reduced from 1.0 for more signals
  sentiment_threshold: -0.1  # Added negative threshold for contrarian signals
  twitter_query: ""
  atr_window: 12  # Reduced from 14 for faster response
  volume_window: 15  # Reduced from 20 for faster response
  jump_mult: 3.5  # Increased from 3.0 for better jump detection
  volume_mult: 3.5  # Increased from 3.0 for better confirmation
  vol_spike_thr: null

maker_spread:
  size_usd: 800.0  # Reduced from 1000.0 for more opportunities
  tick_size: 0.008  # Reduced from 0.01 for tighter spreads
  max_spread_bp: 8.0  # Reduced from 10.0 for tighter spreads
  edge_margin_bp: 0.5  # Added edge margin for better profitability
  queue_timeout_ms: 3000  # Reduced from 5000 for faster response
  max_live_quotes: 3  # Increased from 2 for more opportunities

hft_engine:
  telemetry:
    batch_summary_secs: 45  # Reduced from 60 for faster updates
  dry_run: true
